Use new Github action push config
mattermost/matterwick pull request #45
Opened 2023-02-01 23:28 UTC by gabrieljackson

Another attempt to get docker builds working.

```release-note
None
```

2023-02-02 06:09 UTC, spirosoik approved these changes

2023-02-02 10:01 UTC, fmartingr requested changes
According to the action documentation, you can't use `username/password`... You need to use the `docker-login` action first, and then this one, from the example [in the docs](https://github.com/docker/build-push-action#git-context) should be something like this (I'm posting the example for the latest version v4, but [it's the same for v3](https://github.com/docker/build-push-action/tree/v3.3.1#git-context)):

```yaml
- name: Login to Docker Hub
  uses: docker/login-action@v2
  with:
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_TOKEN }}

- name: build-push-tag
  uses: docker/build-push-action@v3
  with:
    tags: mattermost/matterwick:${{ github.ref_name }}
    push: ${{ startsWith(github.ref, 'refs/tags/') }}

- name: build-push-master
  uses: docker/build-push-action@v3
  with:
    tags: mattermost/matterwick:${{ github.latest }}
    push: ${{ startsWith(github.ref, 'refs/heads/master') }}
```

2023-02-03 15:35 UTC, gabrieljackson commented
@fmartingr thanks for the suggestions, I just updated everything and verified that docker login works on another branch. Please take a look and let me know what you think.

2023-02-04 06:54 UTC, fmartingr approved these changes
This looks good to me, you only need to use a `sha` on the push action as well and this should be good to go :)

2023-02-04 18:05 UTC, merged